name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  geolocator: ^13.0.3
  geocoding: ^3.0.0
  shared_preferences: ^2.5.2

# dependencies:
#   path: ^1.8.0

# dev_dependencies: